services:
  - type: web
    name: skin-watch-ar
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: skin-watch-ar-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: VERTEX_PROJECT
        value: "94890171980"
      - key: VERTEX_ENDPOINT_ID
        value: "6896410158050574336"
      - key: VERTEX_LOCATION
        value: us-central1

databases:
  - name: skin-watch-ar-db
    plan: free
